using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetBharat.IdentityService.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public."map_FormRole_right" (
                    "RoleFormRightId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RoleId" integer NOT NULL,
                    "FormId" integer NOT NULL,
                    "CanRead" boolean NOT NULL,
                    "CanWrite" boolean NOT NULL,
                    "CanDelete" boolean NOT NULL,
                    "CanExport" boolean NOT NULL,
                    "CanAll" boolean NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public."mst_account" (
                    "AccountId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "AccountCode" text NOT NULL,
                    "AccountName" text NOT NULL,
                    "AccountType" text NOT NULL,
                    "Fk_userid" integer NOT NULL,
                    "ParentAccountId" integer NULL,
                    "HierarchyPath" text NOT NULL,
                    "PrimaryDomain" text NOT NULL,
                    "Status" text NOT NULL,
                    "CreatedOn" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public."mst_city" (
                    "CityId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "StateId" integer NOT NULL,
                    "CityName" text NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public."mst_country" (
                    "CountryId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Iso2Code" text NOT NULL,
                    "Iso3Code" text NOT NULL,
                    "CountryName" text NOT NULL,
                    "MobileDialCode" text NOT NULL,
                    "CurrencyCode" text NOT NULL,
                    "CurrencySymbol" text NOT NULL,
                    "TimezoneName" text NOT NULL,
                    "UtcOffset" text NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public."mst_form" (
                    "FormId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FormCode" text NOT NULL,
                    "FormName" text NOT NULL,
                    "ModuleName" text NOT NULL,
                    "PageUrl" text NOT NULL,
                    "PageComponent" text NOT NULL,
                    "IconName" text NOT NULL,
                    "SortOrder" integer NULL,
                    "IsMenu" boolean NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "ParentFormId" integer NULL,
                    "IsVisible" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public."mst_role" (
                    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RoleCode" text NOT NULL,
                    "RoleName" text NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public."mst_state" (
                    "StateId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "CountryId" integer NOT NULL,
                    "StateCode" text NOT NULL,
                    "StateName" text NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public."Users" (
                    "UserId" uuid PRIMARY KEY,
                    "AccountId" integer NOT NULL,
                    "roleId" integer NOT NULL,
                    "Role" text NOT NULL,
                    "GlobalUserCode" text NULL,
                    "FirstName" text NOT NULL,
                    "LastName" text NOT NULL,
                    "Email" text NOT NULL,
                    "MobileNo" text NOT NULL,
                    "CountryCode" text NOT NULL,
                    "Timezone" text NOT NULL,
                    "Language" text NOT NULL,
                    "Password_hash" text NOT NULL,
                    "Status" boolean NOT NULL,
                    "UserStatusLkpId" integer NOT NULL,
                    "EmailVerified" boolean NOT NULL,
                    "MobileVerified" boolean NOT NULL,
                    "TwoFactorEnabled" boolean NOT NULL,
                    "LastLoginAt" timestamp with time zone NULL,
                    "ReferralCode" text NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "RefreshToken" text NULL,
                    "RefreshTokenExpiry" timestamp with time zone NOT NULL,
                    "PasswordResetTokenHash" text NULL,
                    "PasswordResetExpiry" timestamp with time zone NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_map_FormRole_right_RoleId_FormId"
                    ON public."map_FormRole_right" ("RoleId", "FormId");

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_mst_city_StateId_CityName"
                    ON public."mst_city" ("StateId", "CityName");

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_mst_state_CountryId_StateCode"
                    ON public."mst_state" ("CountryId", "StateCode");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "map_FormRole_right");

            migrationBuilder.DropTable(
                name: "mst_account");

            migrationBuilder.DropTable(
                name: "mst_city");

            migrationBuilder.DropTable(
                name: "mst_country");

            migrationBuilder.DropTable(
                name: "mst_form");

            migrationBuilder.DropTable(
                name: "mst_role");

            migrationBuilder.DropTable(
                name: "mst_state");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
