using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FleetBharat.IdentityService.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260421120000_CreateDeviceModels")]
    public class CreateDeviceModels : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public."DeviceModels" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Code" character varying(50) NOT NULL,
                    "Name" character varying(150) NOT NULL,
                    "Description" text NULL,
                    "ManufacturerId" integer NOT NULL,
                    "DeviceCategoryId" integer NOT NULL,
                    "ProtocolType" character varying(50) NOT NULL,
                    "IsEnabled" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    "UpdatedAt" timestamp with time zone NULL,
                    "IsDeleted" boolean NOT NULL DEFAULT FALSE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DeviceModels_Code_Active"
                    ON public."DeviceModels" ("Code")
                    WHERE "IsDeleted" = FALSE;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS public."DeviceModels";""");
        }
    }
}
