using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FleetBharat.IdentityService.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260421130000_CreateVehicleCompliance")]
    public class CreateVehicleCompliance : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public."vehicle_compliance" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "AccountId" integer NOT NULL,
                    "VehicleId" integer NOT NULL,
                    "ComplianceType" character varying(50) NOT NULL,
                    "DocumentNumber" character varying(100) NOT NULL,
                    "IssueDate" timestamp with time zone NOT NULL,
                    "ExpiryDate" timestamp with time zone NOT NULL,
                    "ReminderBeforeDays" integer NOT NULL DEFAULT 7,
                    "DocumentPath" character varying(500) NULL,
                    "DocumentFileName" character varying(255) NULL,
                    "DocumentContentType" character varying(100) NULL,
                    "Remarks" text NULL,
                    "CreatedBy" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    "UpdatedBy" integer NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    "IsDeleted" boolean NOT NULL DEFAULT FALSE
                );

                CREATE INDEX IF NOT EXISTS "IX_vehicle_compliance_account"
                    ON public."vehicle_compliance" ("AccountId");

                CREATE INDEX IF NOT EXISTS "IX_vehicle_compliance_vehicle"
                    ON public."vehicle_compliance" ("VehicleId");

                CREATE INDEX IF NOT EXISTS "IX_vehicle_compliance_expiry"
                    ON public."vehicle_compliance" ("ExpiryDate");

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_vehicle_compliance_document_active"
                    ON public."vehicle_compliance" ("VehicleId", "ComplianceType", "DocumentNumber")
                    WHERE "IsDeleted" = FALSE;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS public."vehicle_compliance";""");
        }
    }
}
