using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FleetBharat.IdentityService.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260428100000_CreateFormConfigurationTables")]
    public class CreateFormConfigurationTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public."form_pages" (
                    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "page_key" character varying(100) NOT NULL,
                    "page_name" character varying(150) NOT NULL,
                    "is_active" boolean NOT NULL DEFAULT TRUE,
                    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    "updated_at" timestamp with time zone NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_form_pages_page_key"
                    ON public."form_pages" ("page_key");

                INSERT INTO public."form_pages" ("page_key", "page_name", "is_active", "created_at", "updated_at")
                VALUES
                    ('trip_create', 'Trip Create', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                    ('vehicle', 'Vehicle', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                    ('driver', 'Driver', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                ON CONFLICT ("page_key") DO UPDATE
                SET
                    "page_name" = EXCLUDED."page_name",
                    "is_active" = EXCLUDED."is_active",
                    "updated_at" = CURRENT_TIMESTAMP;

                CREATE TABLE IF NOT EXISTS public."form_fields" (
                    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "page_key" character varying(100) NOT NULL,
                    "field_key" character varying(100) NOT NULL,
                    "field_label" character varying(150) NOT NULL,
                    "field_type" character varying(50) NOT NULL,
                    "is_active" boolean NOT NULL DEFAULT TRUE,
                    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    "updated_at" timestamp with time zone NULL,
                    CONSTRAINT "FK_form_fields_form_pages_page_key"
                        FOREIGN KEY ("page_key")
                        REFERENCES public."form_pages" ("page_key")
                        ON DELETE RESTRICT
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_form_fields_page_key_field_key"
                    ON public."form_fields" ("page_key", "field_key");

                CREATE INDEX IF NOT EXISTS "IX_form_fields_page_key"
                    ON public."form_fields" ("page_key");

                CREATE TABLE IF NOT EXISTS public."account_form_configurations" (
                    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "account_id" integer NOT NULL,
                    "page_key" character varying(100) NOT NULL,
                    "field_id" integer NOT NULL,
                    "visible" boolean NOT NULL DEFAULT FALSE,
                    "required" boolean NOT NULL DEFAULT FALSE,
                    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    "updated_at" timestamp with time zone NULL,
                    CONSTRAINT "FK_account_form_configurations_account"
                        FOREIGN KEY ("account_id")
                        REFERENCES public."mst_account" ("AccountId")
                        ON DELETE RESTRICT,
                    CONSTRAINT "FK_account_form_configurations_page_key"
                        FOREIGN KEY ("page_key")
                        REFERENCES public."form_pages" ("page_key")
                        ON DELETE RESTRICT,
                    CONSTRAINT "FK_account_form_configurations_field_id"
                        FOREIGN KEY ("field_id")
                        REFERENCES public."form_fields" ("id")
                        ON DELETE RESTRICT
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_account_form_configurations_account_page_field"
                    ON public."account_form_configurations" ("account_id", "page_key", "field_id");

                CREATE INDEX IF NOT EXISTS "IX_account_form_configurations_account_page"
                    ON public."account_form_configurations" ("account_id", "page_key");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS public."account_form_configurations";
                DROP TABLE IF EXISTS public."form_fields";
                DROP TABLE IF EXISTS public."form_pages";
                """);
        }
    }
}
